const SYSTEM_BUSY = 'SYSTEM_BUSY'
const NOT_TOKEN = 'NOT_TOKEN'
const TOKEN_OVERTIME = 'TOKEN_OVERTIME'
const TOKEN_ERROR = 'TOKEN_ERROR'
const NOT_SNO = 'NOT_SNO'
const AUTH_SNO_ERR = 'AUTH_SNO_ERR'
const SNO_IF_EXISTS = 'SNO_IF_EXISTS'
const NOT_USER = 'NOT_USER'
const SNO_IS_BINDING = 'SNO_IS_BINDING'

module.exports = {
  SYSTEM_BUSY,
  NOT_TOKEN,
  TOKEN_OVERTIME,
  TOKEN_ERROR,
  NOT_SNO,
  AUTH_SNO_ERR,
  SNO_IF_EXISTS,
  NOT_USER,
  SNO_IS_BINDING
}