const SYSTEM_BUSY = 'SYSTEM_BUSY'
const NOT_TOKEN = 'NOT_TOKEN'
const TOKEN_OVERTIME = 'TOKEN_OVERTIME'
const TOKEN_ERROR = 'TOKEN_ERROR'
const NOT_SNO = 'NOT_SNO'
const AUTH_SNO_ERR = 'AUTH_SNO_ERR'
const SNO_IF_EXISTS = 'SNO_IF_EXISTS'
const NOT_USER = 'NOT_USER'
const SNO_IS_BINDING = 'SNO_IS_BINDING'
const BUSY_SERVICE = 'BUSY_SERVICEB'
const PARAMS_ERROR = 'PARAMS_ERROR'
const DELETE_ERROR = 'DELETE_ERROR'
const SNO_MISMATCH = 'SNO_MISMATCH'

module.exports = {
  SYSTEM_BUSY,
  NOT_TOKEN,
  TOKEN_OVERTIME,
  TOKEN_ERROR,
  NOT_SNO,
  AUTH_SNO_ERR,
  SNO_IF_EXISTS,
  NOT_USER,
  SNO_IS_BINDING,
  BUSY_SERVICE,
  PARAMS_ERROR,
  DELETE_ERROR,
  SNO_MISMATCH
}